default_config:

frontend:
  themes: !include_dir_merge_named themes

lovelace:
  mode: yaml
  dashboards:
    lovelace-home:
      mode: yaml
      filename: lovelace/home.yaml
      title: Home
      icon: mdi:home-outline

homekit:
  filter:
    include_entities:
      - script.hello
      - script.goodbye

shell_command:
  git_pull_config: "git -C /config pull --rebase"

input_boolean:
  guest_mode:
    name: Guest Mode
    initial: false
    icon: mdi:account-multiple

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

logger:
  default: info
