default_config:

lovelace:
  mode: yaml
  dashboards:
    lovelace-Ï€home:
      mode: yaml
      filename: lovelace/home.yaml
      title: Home
      icon: mdi:home-outline

homekit:
  filter:
    include_entities:
      - script.hello
      - script.goodbye

shell_command:
  git_pull_config: "git -C /config pull --rebase"

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

logger:
  default: info
