
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

lovelace:
  mode: yaml
  resources: []
  dashboards:
    lovelace-home:
      mode: yaml
      filename: lovelace/home.yaml
      title: Home New
      icon: mdi:home-outline

homekit:
  filter:
    include_entities:
      - script.hello
      - script.goodbye

device_tracker:
  - platform: ping
    hosts:
      apple_watch: 192.168.1.XXX  # Replace with your watch's IP

shell_command:
  git_pull_config: "git -C /config pull --rebase"

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

logger:
  default: info
